export const paths = {
  home: "/",
  marketplace: "/marketplace",
  availableProviders: "/prestataires",
  missions: "/missions",
  missionDetail: (id?: string) => id ? `/missions/${id}` : "/missions/:id",
  createMission: "/create-mission",
  features: "/features",
  profile: "/profile",
  messages: "/messages",
  legal: "/legal",
  dashboard: "/dashboard",
  aiFeatures: "/ai-features",
  aiTest: "/ai-test",
  aiDashboard: "/ai-dashboard",
  projectImprove: "/project-improve",
  aiAdvanced: "/ai-advanced",
  demoMissions: "/demo/missions",
  demoProfiles: "/demo/profils",
  demoIA: "/demo/ia",
  services: "/services",
  servicesByType: (type?: string) => type ? `/services/${type}` : "/services/:type",
  profileDashboard: "/profil",
  profileEdit: "/profil/editer",
  profilePublic: (userId?: string) => userId ? `/profil/${userId}` : "/profil/:userId",
  notFound: "/404",
} as const;